#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CustomBalloon.Resource", IsApplication=false)]

namespace CustomBalloon
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public static int accentColor = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int balloonColor = 2130771971;
			
			// aapt resource value: 0x7f010000
			public static int showEmoji = 2130771968;
			
			// aapt resource value: 0x7f010005
			public static int text = 2130771973;
			
			// aapt resource value: 0x7f010004
			public static int textColor = 2130771972;
			
			// aapt resource value: 0x7f010006
			public static int textSize = 2130771974;
			
			// aapt resource value: 0x7f010001
			public static int triangleHeight = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MyBalloonView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 2
			public static int MyBalloonView_accentColor = 2;
			
			// aapt resource value: 3
			public static int MyBalloonView_balloonColor = 3;
			
			// aapt resource value: 0
			public static int MyBalloonView_showEmoji = 0;
			
			// aapt resource value: 5
			public static int MyBalloonView_text = 5;
			
			// aapt resource value: 4
			public static int MyBalloonView_textColor = 4;
			
			// aapt resource value: 6
			public static int MyBalloonView_textSize = 6;
			
			// aapt resource value: 1
			public static int MyBalloonView_triangleHeight = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
